# Pandas DataFrame Exercises: Student Performance

This notebook gives you a new DataFrame exercise idea using **student performance data** instead of countries.

You will practice:

- Creating a DataFrame
- Exploring rows and columns
- Selecting columns
- Filtering data
- Adding new columns
- Sorting data
- Using `loc` and `iloc`
- Using simple statistics
- Grouping data with `groupby`

In [1]:
import pandas as pd

## Dataset Idea

We will create a DataFrame about students and their grades.

Each row represents one student.

In [2]:
students_data = {
    "student_name": ["Sara", "Omar", "Lina", "Ahmed", "Mona", "Youssef", "Nora", "Hassan"],
    "class": ["A", "A", "B", "B", "A", "C", "C", "B"],
    "math_score": [88, 72, 95, 60, 78, 85, 90, 66],
    "english_score": [92, 75, 89, 70, 84, 80, 94, 68],
    "science_score": [85, 70, 96, 65, 82, 88, 91, 72],
    "attendance_rate": [96, 85, 98, 76, 90, 88, 97, 80],
    "study_hours": [8, 5, 10, 3, 6, 7, 9, 4]
}

students = pd.DataFrame(students_data)
students

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours
0,Sara,A,88,92,85,96,8
1,Omar,A,72,75,70,85,5
2,Lina,B,95,89,96,98,10
3,Ahmed,B,60,70,65,76,3
4,Mona,A,78,84,82,90,6
5,Youssef,C,85,80,88,88,7
6,Nora,C,90,94,91,97,9
7,Hassan,B,66,68,72,80,4

## Exercise 1: Explore the DataFrame

Write code to answer the following:

1. Display the first 5 rows.
2. Display the last 3 rows.
3. Show the shape of the DataFrame.
4. Show the column names.
5. Show the data types.
6. Use `info()` to understand the DataFrame.

In [70]:
# Your code here
students.head(5)

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
3,Ahmed,B,60,70,65,76,3,65.000000,Fail
4,Mona,A,78,84,82,90,6,81.333333,Pass

In [71]:
students.tail(3)

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
5,Youssef,C,85,80,88,88,7,84.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass
7,Hassan,B,66,68,72,80,4,68.666667,Fail

In [72]:
f" {students.shape}"

' (8, 9)'

In [73]:
students.columns

Index(['student_name', 'class', 'math_score', 'english_score', 'science_score',
       'attendance_rate', 'study_hours', 'average_score', 'status'],
      dtype='object')

In [74]:
students.dtypes

student_name        object
class               object
math_score           int64
english_score        int64
science_score        int64
attendance_rate      int64
study_hours          int64
average_score      float64
status              object
dtype: object

In [75]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_name     8 non-null      object
 1   class            8 non-null      object
 2   math_score       8 non-null      int64
 3   english_score    8 non-null      int64
 4   science_score    8 non-null      int64
 5   attendance_rate  8 non-null      int64
 6   study_hours      8 non-null      int64
 7   average_score    8 non-null      float64
 8   status           8 non-null      object
dtypes: float64(1), int64(5), object(3)
memory usage: 708.0+ bytes

## Exercise 2: Select Columns

Write code to select:

1. Only the `student_name` column.
2. The `student_name` and `math_score` columns.
3. The three score columns: `math_score`, `english_score`, and `science_score`.

In [40]:
# Your code here
students["student_name"]

0       Sara
1       Omar
2       Lina
3      Ahmed
4       Mona
5    Youssef
6       Nora
7     Hassan
Name: student_name, dtype: object

In [39]:
# Your code here
students[["student_name", "math_score"]]

  student_name  math_score
0         Sara          88
1         Omar          72
2         Lina          95
3        Ahmed          60
4         Mona          78
5      Youssef          85
6         Nora          90
7       Hassan          66

In [38]:
students[["student_name", "math_score","science_score"]]

  student_name  math_score  science_score
0         Sara          88             85
1         Omar          72             70
2         Lina          95             96
3        Ahmed          60             65
4         Mona          78             82
5      Youssef          85             88
6         Nora          90             91
7       Hassan          66             72

## Exercise 3: Create a New Column

Create a new column called `average_score`.

The average score should be calculated from:

- `math_score`
- `english_score`
- `science_score`

In [11]:
# Your code here
students["average_score"] = (students["math_score"] +
                              students["english_score"] +
                              students["science_score"]) / 3

print(students)
print(f" {type(students['average_score'])}")

  student_name class  math_score  english_score  science_score  \
0         Sara     A          88             92             85
1         Omar     A          72             75             70
2         Lina     B          95             89             96
3        Ahmed     B          60             70             65
4         Mona     A          78             84             82
5      Youssef     C          85             80             88
6         Nora     C          90             94             91
7       Hassan     B          66             68             72

   attendance_rate  study_hours  average_score
0               96            8      88.333333
1               85            5      72.333333
2               98           10      93.333333
3               76            3      65.000000
4               90            6      81.333333
5               88            7      84.333333
6               97            9      91.666667
7               80            4      68.666667
 <class 'pandas.core.series.Series'>

## Exercise 4: Add a Pass / Fail Column

Create a new column called `status`.

If the student's `average_score` is **70 or more**, the status should be `"Pass"`.

Otherwise, the status should be `"Fail"`.

In [68]:
# Your code here
import numpy as np
students["status"] = students["average_score"].apply(lambda x: "Pass" if x >= 70 else "Fail")
students

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
3,Ahmed,B,60,70,65,76,3,65.000000,Fail
4,Mona,A,78,84,82,90,6,81.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass
7,Hassan,B,66,68,72,80,4,68.666667,Fail

## Exercise 5: Filter Rows

Write code to find:

1. Students who got more than 80 in math.
2. Students whose attendance rate is less than 85.
3. Students who studied more than 6 hours.
4. Students who passed.

In [43]:
# Your code here
students[students["math_score"] > 80]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass

In [45]:
students[students["math_score"] < 80]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
1,Omar,A,72,75,70,85,5,72.333333,Pass
3,Ahmed,B,60,70,65,76,3,65.000000,Fail
4,Mona,A,78,84,82,90,6,81.333333,Pass
7,Hassan,B,66,68,72,80,4,68.666667,Fail

In [46]:
students[students["study_hours"] > 6]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass

In [47]:
students[students["status"] == "Pass"]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
4,Mona,A,78,84,82,90,6,81.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass

## Exercise 6: Multiple Conditions

Write code to find:

1. Students with `average_score` above 85 and attendance above 90.
2. Students from class `"B"` who passed.
3. Students who studied less than 5 hours or failed.

In [48]:
# Your code here
students[(students["average_score"] > 85) & (students["attendance_rate"] > 90)]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass

In [49]:
students[(students["class"] == "B") & (students["status"] == "Pass")]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
2,Lina,B,95,89,96,98,10,93.333333,Pass

In [50]:
students[(students["study_hours"] < 5) | (students["status"] == "Fail")]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
3,Ahmed,B,60,70,65,76,3,65.000000,Fail
7,Hassan,B,66,68,72,80,4,68.666667,Fail

## Exercise 7: Sorting

Write code to:

1. Sort students by `average_score` from highest to lowest.
2. Sort students by `attendance_rate` from lowest to highest.
3. Show the top 3 students based on `average_score`.

In [51]:
# Your code here
students.sort_values(by="average_score", ascending=False)

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
2,Lina,B,95,89,96,98,10,93.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass
0,Sara,A,88,92,85,96,8,88.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
4,Mona,A,78,84,82,90,6,81.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
7,Hassan,B,66,68,72,80,4,68.666667,Fail
3,Ahmed,B,60,70,65,76,3,65.000000,Fail

In [52]:
students.sort_values(by="attendance_rate")

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
3,Ahmed,B,60,70,65,76,3,65.000000,Fail
7,Hassan,B,66,68,72,80,4,68.666667,Fail
1,Omar,A,72,75,70,85,5,72.333333,Pass
5,Youssef,C,85,80,88,88,7,84.333333,Pass
4,Mona,A,78,84,82,90,6,81.333333,Pass
0,Sara,A,88,92,85,96,8,88.333333,Pass
6,Nora,C,90,94,91,97,9,91.666667,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass

In [24]:
students.iloc[0:3]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass

## Exercise 8: Use `loc`

Use `loc` to:

1. Show the row of student `"Sara"`.
2. Show the `math_score` and `english_score` of `"Lina"`.
3. Show all students from class `"A"` with their names and average scores.

In [35]:
# Tip: You may first set student_name as the index
students_ind = students.set_index("student_name")

# Your code here
students_ind.loc["Sara"]

class                      A
math_score                88
english_score             92
science_score             85
attendance_rate           96
study_hours                8
average_score      88.333333
status                  Pass
Name: Sara, dtype: object

In [36]:
students_ind.loc["Lina", ["math_score", "english_score"]]

math_score       95
english_score    89
Name: Lina, dtype: object

In [41]:
students_ind[students_ind["class"] == "A"]

,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
student_name,,,,,,,,
Sara,A,88,92,85,96,8,88.333333,Pass
Omar,A,72,75,70,85,5,72.333333,Pass
Mona,A,78,84,82,90,6,81.333333,Pass

## Exercise 9: Use `iloc`

Use `iloc` to:

1. Select the first row.
2. Select the first 3 rows.
3. Select the first 4 rows and first 3 columns.
4. Select the last row.

In [53]:
# Your code here
students.iloc[0]

student_name            Sara
class                      A
math_score                88
english_score             92
science_score             85
attendance_rate           96
study_hours                8
average_score      88.333333
status                  Pass
Name: 0, dtype: object

In [54]:
students.iloc[0:4]

,student_name,class,math_score,english_score,science_score,attendance_rate,study_hours,average_score,status
0,Sara,A,88,92,85,96,8,88.333333,Pass
1,Omar,A,72,75,70,85,5,72.333333,Pass
2,Lina,B,95,89,96,98,10,93.333333,Pass
3,Ahmed,B,60,70,65,76,3,65.000000,Fail

In [57]:
students.iloc[0:5 , 0:4]

  student_name class  math_score  english_score
0         Sara     A          88             92
1         Omar     A          72             75
2         Lina     B          95             89
3        Ahmed     B          60             70
4         Mona     A          78             84

In [58]:
students.iloc[-1]

student_name          Hassan
class                      B
math_score                66
english_score             68
science_score             72
attendance_rate           80
study_hours                4
average_score      68.666667
status                  Fail
Name: 7, dtype: object

## Exercise 10: Summary Statistics

Write code to answer:

1. What is the average math score?
2. What is the highest English score?
3. What is the lowest science score?
4. What is the average attendance rate?
5. Use `describe()` on the DataFrame.

In [59]:
# Your code here
students["math_score"].mean()

np.float64(79.25)

In [60]:
students["english_score"].max()

94

In [61]:
students["science_score"].min()

65

In [62]:
students["attendance_rate"].mean()

np.float64(88.75)

In [63]:
students.describe()

,math_score,english_score,science_score,attendance_rate,study_hours,average_score
count,8.000000,8.000000,8.000000,8.000000,8.00000,8.000000
mean,79.250000,81.500000,81.125000,88.750000,6.50000,80.625000
std,12.383745,9.913915,11.012169,8.119641,2.44949,10.776867
min,60.000000,68.000000,65.000000,76.000000,3.00000,65.000000
25%,70.500000,73.750000,71.500000,83.750000,4.75000,71.416667
50%,81.500000,82.000000,83.500000,89.000000,6.50000,82.833333
75%,88.500000,89.750000,88.750000,96.250000,8.25000,89.166667
max,95.000000,94.000000,96.000000,98.000000,10.00000,93.333333

## Exercise 11: GroupBy

Use `groupby` to answer:

1. What is the average score for each class?
2. What is the average attendance rate for each class?
3. What is the average study hours for each class?

In [64]:
# Your code here
students.groupby("class")["average_score"].mean()

class
A    80.666667
B    75.666667
C    88.000000
Name: average_score, dtype: float64

In [65]:
students.groupby("class")["attendance_rate"].mean()

class
A    90.333333
B    84.666667
C    92.500000
Name: attendance_rate, dtype: float64

In [66]:
students.groupby("class")["study_hours"].mean()

class
A    6.333333
B    5.666667
C    8.000000
Name: study_hours, dtype: float64

## Exercise 12: Challenge

Create a column called `performance_level`.

Rules:

- If `average_score` is 90 or more → `"Excellent"`
- If `average_score` is 80 to 89 → `"Very Good"`
- If `average_score` is 70 to 79 → `"Good"`
- Otherwise → `"Needs Improvement"`

Then display:

1. Student name
2. Average score
3. Performance level

In [84]:
# Your code here
def assign_performance(score):
    if score >= 90:
        return "Excellent"
    elif score >= 80:
        return "Very Good"
    elif score >= 70:
        return "Good"
    else:
        return "Needs Improvement"

students["performance_level"] = students["average_score"].apply(assign_performance)

In [85]:
students[["student_name", "average_score", "performance_level"]]

  student_name  average_score  performance_level
0         Sara      88.333333          Very Good
1         Omar      72.333333               Good
2         Lina      93.333333          Excellent
3        Ahmed      65.000000  Needs Improvement
4         Mona      81.333333          Very Good
5      Youssef      84.333333          Very Good
6         Nora      91.666667          Excellent
7       Hassan      68.666667  Needs Improvement